language: node_js
node_js:
  - node

notifications:
  slack:
    rooms:
      - secure: FILL_IN_SECURE_TOKEN
    if: fork = false

cache: yarn

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn test

after_success:
  - codecov
